Changed scripting to download pipeline if needed

diff --git a/.github/workflows/eera.yml b/.github/workflows/eera.yml
--- a/.github/workflows/eera.yml
+++ b/.github/workflows/eera.yml
@@ -9,7 +9,7 @@ jobs:
     strategy:
         fail-fast: false
         matrix:
-                os: ['ubuntu-20.04', 'macos-latest']
+                os: ['ubuntu-20.04'] #, 'macos-latest']
                 config: [{
                             compiler: gcc,
                             compilerpp: g++
@@ -107,13 +107,26 @@ jobs:
           exit 1
         fi
 
+    - name: Run data pipeline regression tests
+      env:
+            PYTHONPATH: data_pipeline_api
+      run: |
+        source .venv/bin/activate
+        ./scripts/RunRegressionTests.sh 1 24 -d
+        if [ $? -eq 0 ]; then
+          echo "Data pipeline Regression tests completed successfully"
+          exit 0
+        else
+          echo "Data pipeline Regression tests failed"
+          exit 1
+        fi
+
     - name: Run unit tests
       env:
             PYTHONPATH: data_pipeline_api
       run: |
         source .venv/bin/activate
-        cd build
-        ./bin/Covid19EERAModel-unit_tests
+        ./scripts/RunUnitTests.sh
         if [ $? -eq 0 ]; then
           echo "Unit tests completed successfully"
           exit 0
