Added macOS testing

diff --git a/.github/workflows/eera.yml b/.github/workflows/eera.yml
--- a/.github/workflows/eera.yml
+++ b/.github/workflows/eera.yml
@@ -3,8 +3,61 @@ name: CI
 on: [push]
 
 jobs:
-  build:
-    runs-on: ubuntu-18.04
+  build_macOS_latest:
+    runs-on: macos-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install Brew
+        run : /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
+
+      - name: Install GSL
+        run : brew update && brew install gsl
+
+      - name: Install cppcheck
+        run: brew install cppcheck
+
+      - name: Compile
+        run: |
+          mkdir build
+          cd build
+          cmake ..
+          make
+          
+      - name: Run regression tests
+        run: |
+          ./scripts/RunRegressionTests.sh
+          if [ $? -eq 0 ]; then
+            echo "Regression tests completed successfully"
+            exit 0
+          else
+            echo "Regression tests failed"
+            exit 1
+          fi
+
+      - name: Run unit tests
+        run: |
+          ./build/bin/Covid19EERAModel-unit_tests
+          if [ $? -eq 0 ]; then
+            echo "Unit tests completed successfully"
+            exit 0
+          else
+            echo "Unit tests failed"
+            exit 1
+          fi
+      - name: Run Cpp Check with internal parser
+        run: |
+           echo "Running CppCheck on files in 'src' with internal parser"
+           for i in src/*.h src/*.cpp test/unit/*.cpp; do 
+             if cppcheck --language=c++ --std=c++11 --error-exitcode=1 $i; then
+               continue
+             else
+               exit 1
+             fi
+           done
+
+  build_Ubuntu_latest:
+    runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v2
@@ -53,4 +106,4 @@ jobs:
              exit 1
            fi
          done
-
+  
