Integrated regression tests into CI
Addresses SCRC-137

diff --git a/.github/workflows/eera.yml b/.github/workflows/eera.yml
--- a/.github/workflows/eera.yml
+++ b/.github/workflows/eera.yml
@@ -19,40 +19,17 @@ jobs:
         cmake ..
         make
         
-    - name: Run test model (short run)
+    - name: Run regression tests
       run: |
-        rm -rf outputs/*.txt
-        cp test/end-to-end/short/parameters.ini data/parameters.ini
-        ./build/bin/Covid19EERAModel
-        
-    - name: Check output files
-      run: |
-        cd outputs
-        
-        nsteps=$(awk -F "=" '/nsteps/ {print $2}' ../data/parameters.ini)
-        board=$(awk -F "=" '/shb_id/ {print $2}' ../data/parameters.ini)
-        
-        failures=0
-        let "upper = $nsteps - 1"
-        for i in $(seq 0 $upper) ; do
-          for f in \
-              output\_abc-smc\_particles\_step$i\_shb$board.txt \
-              output\_abc-smc\_simu_step$i\_shb$board.txt \
-              output\_abc-smc\_ends\_step$i\_shb$board.txt; do
-            if [ ! -f "$f" ]; then
-              echo "Required output file $f not found" >&2
-              failures=$((failures+1))
-            fi
-          done
-        done
-        
-        if [ $failures -gt 0 ]; then
-          echo "Failed due to $failures missing output files" >&2
-          exit 1
+        ./scripts/RunRegressionTests
+        if [ $? -eq 0 ]; then
+          echo "Regression tests completed successfully"
+          exit 0
         else
-          echo "All required output files found"
+          echo "Regression tests failed"
+          exit 1
         fi
-    
+        
     - name: Run unit tests
       run: |
         ./build/bin/Covid19EERAModel-unit_tests
